import type { Locale } from "./i18n";

const copy = {
  overview: ["نمای کلی", "Overview"],
  posts: ["پست‌ها", "Posts"],
  members: ["اعضای ثبت‌شده", "Observed members"],
  alerts: ["هشدارها", "Alerts"],
  events: ["گزارش عملیات", "Activity log"],
  settings: ["تنظیمات کانال", "Chat settings"],
  overviewDescription: ["کانال خود را مدیریت کنید؛ از آخرین تعامل‌ها تا تصمیم‌های نیازمند بررسی شما.", "Manage your chat, from recent interactions to decisions that need your attention."],
  postsDescription: ["انتشار متن و مدیریت رأی‌های دکمه‌های ربات؛ نه واکنش‌های بومی تلگرام.", "Publish text and manage votes from bot buttons, not native Telegram reactions."],
  membersDescription: ["حداکثر ۵۰ حساب ثبت‌شدهٔ اخیر، بر پایهٔ رویدادهایی که ربات دریافت کرده است.", "Up to 50 recently recorded accounts, based on events the bot has received."],
  alertsDescription: ["حداکثر ۵۰ هشدار بررسی‌نشدهٔ اخیر. تصمیم نهایی برای هر حساب با شماست.", "Up to 50 recent unreviewed alerts. You decide what happens to each account."],
  eventsDescription: ["حداکثر ۵۰ عملیات اخیر با نتیجهٔ ثبت‌شده؛ زمان‌ها به وقت تهران.", "Up to 50 recent operations and their recorded outcomes. All times are in Tehran time."],
  settingsDescription: ["قواعد رأی‌دادن و دیدگاه‌ها فقط برای کانال انتخاب‌شده؛ نه تنظیمات سراسری سامانه.", "Voting and comment rules for the selected chat only, not platform-wide settings."],
  currentChat: ["کانال انتخاب‌شده", "Selected chat"],
  switchChat: ["تغییر کانال", "Switch chat"],
  yourChats: ["کانال‌های در دسترس شما", "Your accessible chats"],
  chatScope: ["حداکثر ۵۰ اتصال اخیر در دسترسی شما؛ وضعیت ثبت‌شده، تضمین اتصال لحظه‌ای نیست.", "Up to 50 recent connections you can access. Recorded status does not guarantee a live connection."],
  active: ["فعال در سامانه", "Active in Darban"],
  inactive: ["غیرفعال در سامانه", "Inactive in Darban"],
  chatAdmin: ["نقش شما: مدیر کانال", "Your role: chat admin"],
  sampleRole: ["نقش نمایشی: مدیر کانال", "Sample role: chat admin"],
  noChat: ["کانالی انتخاب نشده", "No chat selected"],
  addChat: ["افزودن کانال یا گروه", "Connect a channel or group"],
  connect: ["بررسی و اتصال کانال", "Verify and connect chat"],
  connectTitle: ["اتصال جدید", "New connection"],
  unavailableChat: ["کانال انتخاب‌شده در دسترس شما نیست یا وجود ندارد. از فهرست کانال‌های خود انتخاب کنید.", "The selected chat does not exist or is not available to you. Choose a chat from your list."],
  firstChat: ["اولین کانال را اضافه کنید", "Connect your first chat"],
  firstChatHelp: ["ابتدا ربات را در تلگرام مدیر کنید، سپس شناسهٔ کانال یا گروه را وارد کنید. اتصال تنها پس از بررسی دسترسی‌ها انجام می‌شود.", "Make the bot an admin in Telegram, then enter the channel or group ID. Access is checked before connecting."],
  configurationWarning: ["پیکربندی اتصال کامل نیست. اقدام‌ها تا تکمیل تنظیمات سرور غیرفعال‌اند. داده‌های زیر فقط سوابق پایگاه داده هستند.", "Connection configuration is incomplete. Actions are disabled until server setup is complete. The data below is stored database history only."],
  inactiveWarning: ["این کانال در سامانه غیرفعال است؛ انتشار پست تا فعال شدن اتصال در دسترس نیست.", "This chat is inactive in Darban. Publishing is unavailable until the connection is active."],
  observedWarning: ["این اعداد فقط حساب‌ها و تعامل‌های مشاهده‌شدهٔ ربات هستند؛ نه فهرست کامل اعضای تلگرام. تلگرام فهرست کامل اعضا یا تاریخ ساخت حساب را در اختیار ربات نمی‌گذارد.", "These counts cover only accounts and interactions observed by the bot, not the full Telegram member list. Telegram does not provide a full member list or account creation dates to bots."],
  joinWarning: ["زمان ورود اعضایی که رویداد عضویتشان مشاهده نشده، نامشخص می‌ماند و دورهٔ انتظار برای آن‌ها اعمال نمی‌شود. این قاعده سن حساب تلگرام را بررسی نمی‌کند.", "Members without an observed join event have an unknown join date and no waiting period. This rule does not check the age of a Telegram account."],
  nativeWarning: ["واکنش‌های بومی تلگرام را در تنظیمات کانال، بخش واکنش‌ها، دستی خاموش کنید. ربات نمی‌تواند آن‌ها را خاموش کند؛ در غیر این صورت واکنش‌های بومی از این قواعد عبور می‌کنند.", "Disable native Telegram reactions manually in the channel's Reactions settings. The bot cannot disable them; otherwise native reactions bypass these rules."],
  verificationWarning: ["تأیید حساب یعنی آغاز گفتگوی خصوصی با ربات؛ نه اثبات هویت فرد.", "Verification means starting a private conversation with the bot, not proof of identity."],
  noAutomaticBans: ["تقارن زمانی به‌تنهایی نشانهٔ تخلف نیست. شواهد را بررسی و برای هر حساب جداگانه تصمیم بگیرید؛ هیچ حسابی خودکار مسدود نمی‌شود.", "Timing alone is not evidence of abuse. Review the evidence and decide for each account separately. No account is banned automatically."],
  moderationWarning: ["مسدود کردن در تلگرام ممکن است تاریخچهٔ پیام‌ها را حذف کند. رفع مسدودیت، عضویت یا پیام‌های حذف‌شده را بازنمی‌گرداند.", "Banning in Telegram may delete message history. Unbanning does not restore membership or deleted messages."],
  unknownWarning: ["«نامشخص» یعنی نتیجهٔ قطعی دریافت نشده است؛ نه موفقیت و نه شکست. پیش از تکرار اقدام، گزارش عملیات و وضعیت تلگرام را بررسی کنید.", "Unknown means no definitive outcome was received, not success or failure. Check the activity log and Telegram before repeating an action."],
  recordedMembers: ["عضو ثبت‌شده", "Observed members"],
  recordedPosts: ["پست ثبت‌شده", "Recorded posts"],
  openAlerts: ["هشدار بررسی‌نشده", "Unreviewed alerts"],
  reviewQueue: ["نیازمند بررسی شما", "Needs your review"],
  reviewQueueHelp: ["شواهد را ببینید؛ اقدام روی حساب‌ها فقط با تأیید شما انجام می‌شود.", "Inspect the evidence. Actions on accounts require your explicit confirmation."],
  reviewAlerts: ["بررسی هشدارها", "Review alerts"],
  writePost: ["نوشتن پست", "Write a post"],
  latestPosts: ["آخرین پست‌ها", "Latest posts"],
  latestPostsHelp: ["۳ پست اخیر و رأی‌های ثبت‌شده در سامانه", "The 3 latest posts and votes recorded in Darban"],
  allPosts: ["همهٔ پست‌های اخیر", "View recent posts"],
  noPosts: ["هنوز پستی ثبت نشده", "No posts recorded yet"],
  noPostsHelp: ["از بخش انتشار، یک پست متنی با دکمه‌های رأی‌گیری بسازید. فقط پست‌های ثبت‌شده در این سامانه نمایش داده می‌شوند.", "Publish a text post with voting buttons. Only posts recorded in Darban appear here."],
  publishTitle: ["انتشار پست جدید", "Publish a new post"],
  publishHelp: ["پیش از انتشار، متن و مقصد را تأیید خواهید کرد.", "You will confirm the text and destination before publishing."],
  recentPostsHelp: ["حداکثر ۵۰ پست اخیر. شمارنده‌ها مربوط به رأی‌های ثبت‌شده در سامانه‌اند.", "Up to 50 recent posts. Counters reflect votes recorded in Darban."],
  message: ["پیام", "Message"],
  noMessageId: ["بدون شناسهٔ پیام تلگرام", "No Telegram message ID"],
  agree: ["موافقم", "Agree"],
  useful: ["مفید بود", "Useful"],
  question: ["پرسش دارم", "Question"],
  rules: ["قواعد کانال", "Chat rules"],
  rulesHelp: ["این قواعد بر تعامل‌هایی اعمال می‌شوند که ربات دریافت می‌کند.", "These rules apply to interactions received by the bot."],
  editSettings: ["ویرایش تنظیمات", "Edit settings"],
  verification: ["تأیید حساب با ربات", "Bot verification"],
  required: ["الزامی", "Required"],
  disabled: ["غیرفعال", "Disabled"],
  enabled: ["فعال", "Enabled"],
  wait: ["زمان انتظار پس از عضویت", "Waiting period after joining"],
  hours: ["ساعت", "hours"],
  commentGate: ["زمان انتظار دیدگاه‌ها در گروه مرتبط", "Comment waiting period in linked group"],
  latestEvents: ["آخرین عملیات", "Recent activity"],
  allEvents: ["مشاهدهٔ گزارش عملیات", "View activity log"],
  noEvents: ["عملیاتی ثبت نشده", "No activity recorded"],
  noEventsHelp: ["پس از اولین اقدام مدیریتی، نتیجه و عامل آن در این بخش ثبت می‌شود.", "Your first admin action will appear here with its outcome and actor."],
  eventsCaption: ["گزارش عملیات کانال؛ زمان‌ها به وقت تهران", "Chat activity log; times are in Tehran time"],
  actionTime: ["عملیات / زمان", "Action / time"],
  actor: ["عامل", "Actor"],
  target: ["حساب هدف", "Target account"],
  reason: ["دلیل", "Reason"],
  outcome: ["نتیجه", "Outcome"],
  noMembers: ["عضوی در سامانه ثبت نشده", "No members recorded"],
  noMembersHelp: ["تلگرام فهرست کامل اعضای کانال را در اختیار ربات قرار نمی‌دهد. حساب‌ها پس از دریافت رویدادهای عضویت یا تعامل ثبت می‌شوند.", "Telegram does not provide the full channel member list to bots. Accounts are recorded after membership events or interactions."],
  membersCaption: ["حداکثر ۵۰ عضو ثبت‌شدهٔ اخیر؛ نه فهرست کامل اعضای تلگرام", "Up to 50 recently recorded members; not the full Telegram member list"],
  accountId: ["حساب / شناسه", "Account / ID"],
  observedJoin: ["عضویت ثبت‌شده", "Observed join"],
  firstVote: ["اولین رأی", "First vote"],
  adminAction: ["اقدام مدیریتی", "Admin action"],
  banned: ["مسدود", "Banned"],
  present: ["حاضر", "Present"],
  left: ["خارج‌شده", "Left"],
  notVerified: ["تأیید نشده", "Not verified"],
  notRecorded: ["ثبت نشده", "Not recorded"],
  noAlerts: ["هشدار بررسی‌نشده‌ای وجود ندارد", "No unreviewed alerts"],
  noAlertsHelp: ["هشدارهای ثبت‌شده برای بررسی انسانی اینجا قرار می‌گیرند. نبود هشدار، تضمین نبود تخلف نیست.", "Recorded alerts appear here for human review. No alerts does not guarantee no abuse."],
  firstVoteTiming: ["هم‌زمانی اولین رأی‌ها", "First-vote timing cluster"],
  humanReview: ["نیازمند بررسی انسانی", "Needs human review"],
  postId: ["شناسهٔ پست", "Post ID"],
  evidence: ["مشاهدهٔ شواهد ثبت‌شده", "View recorded evidence"],
  evidenceLimit: ["حداکثر ۱۶٬۰۰۰ نویسه از شواهد و ۵۰ شناسه در این نما نمایش داده می‌شود.", "This view shows up to 16,000 evidence characters and 50 account IDs."],
  inspectAccount: ["بررسی حساب", "Review account"],
  noCandidates: ["شناسهٔ قابل اقدام در شواهد پیدا نشد. داده‌های ثبت‌شده را بررسی کنید.", "No actionable account IDs were found in the evidence. Inspect the recorded data."],
  selectedOnly: ["تغییرات فقط برای کانال انتخاب‌شده ذخیره می‌شوند.", "Changes are saved for the selected chat only."],
  sampleData: ["داده‌ها، حساب‌ها و زمان‌ها ساختگی‌اند.", "Data, accounts and timestamps are synthetic."],
  scopedData: ["فقط داده‌های ثبت‌شدهٔ کانال‌های تحت مدیریت شما نمایش داده می‌شوند.", "Only recorded data for chats you manage is shown."],
  timezone: ["زمان‌ها به وقت تهران", "Times shown in Tehran time"],
  publish: ["بررسی و انتشار", "Review and publish"],
  ban: ["مسدود کردن", "Ban account"],
  unban: ["رفع مسدودیت", "Unban account"],
  saveSettings: ["ذخیرهٔ تنظیمات", "Save chat settings"],
  review: ["ثبت به‌عنوان بررسی‌شده", "Mark as reviewed"],
  sync: ["همگام‌سازی شمارنده‌ها", "Sync vote counters"],
  attach: ["ثبت شناسهٔ پیام", "Record message ID"],
  messageIdLabel: ["شناسهٔ پیام در تلگرام", "Telegram message ID"],
  attachHelp: ["نتیجهٔ انتشار این پست قطعی نشد. اگر پست در تلگرام منتشر شده است، روی آن راست‌کلیک کنید، «کپی لینک پیام» را بزنید و عدد پایان لینک را اینجا وارد کنید تا دکمه‌های رأی دوباره کار کنند.", "This post's delivery was never confirmed. If it did reach Telegram, right-click it, copy the message link, and enter the number at the end of that link so its voting buttons work again."],
  chatIdLabel: ["شناسهٔ عددی یا نام کاربری کانال یا گروه", "Channel or group numeric ID or username"],
  connectHelp: ["شناسهٔ عددی یا نام کاربری را وارد کنید. ربات باید مدیر باشد و اجازهٔ ارسال پست و محدود کردن اعضا داشته باشد. دسترسی مدیریتی شما در تلگرام بررسی می‌شود.", "Enter a numeric ID or username. The bot must be an admin with permission to post and restrict members. Your Telegram admin access will be verified."],
  postText: ["متن پست", "Post text"],
  postPlaceholder: ["متنی که می‌خواهید در کانال منتشر شود…", "Write the text to publish in this chat…"],
  characterHelp: ["نویسه؛ فقط متن، با دکمه‌های رأی‌گیری ربات", "characters; text only, with bot voting buttons"],
  of: ["از", "of"],
  destination: ["مقصد", "Destination"],
  account: ["حساب", "Account"],
  actionReason: ["دلیل اقدام", "Reason for action"],
  reasonPlaceholder: ["دلیل قابل ثبت در گزارش عملیات", "Reason to record in the activity log"],
  waitHoursLabel: ["مدت انتظار از زمان عضویت (ساعت)", "Waiting period after joining (hours)"],
  waitRange: ["بین ۰ تا ۱۶۸ ساعت", "Between 0 and 168 hours"],
  verifyBeforeVote: ["تأیید حساب با ربات پیش از رأی دادن", "Require bot verification before voting"],
  gateComments: ["اعمال زمان انتظار پس از عضویت برای دیدگاه‌ها", "Apply the post-join waiting period to comments"],
  discussionId: ["شناسهٔ گروه گفتگوی مرتبط", "Linked discussion group ID"],
  discussionHelp: ["برای کنترل دیدگاه‌ها، گروه مرتبط باید جداگانه ثبت شده باشد و ربات در آن دسترسی مدیریتی داشته باشد. خالی گذاشتن یعنی بدون گروه مرتبط.", "To control comments, register the linked group separately and give the bot admin access there. Leave empty for no linked group."],
  sending: ["در حال ارسال…", "Sending…"],
  publishConfirm: ["این متن برای مخاطبان کانال منتشر شود؟", "Publish this text to the chat's audience?"],
  moderateConfirm: ["این اقدام روی حساب انتخاب‌شده انجام شود؟", "Perform this action on the selected account?"],
  requestError: ["درخواست انجام نشد. وضعیت اتصال و دسترسی را بررسی و دوباره تلاش کنید.", "The request could not be completed. Check your connection and access, then try again."],
  conflictError: ["درخواست با وضعیت فعلی سازگار نیست و نتیجه ممکن است نامشخص باشد. پیش از تلاش دوباره، گزارش عملیات و تلگرام را بررسی کنید؛ شناسهٔ درخواست جدید نسازید.", "The request conflicts with the current state and its outcome may be uncertain. Check the activity log and Telegram before retrying; do not create a new request ID."],
  pendingResult: ["درخواست در انتظار نتیجه است. گزارش عملیات را بررسی کنید.", "The request is awaiting an outcome. Check the activity log."],
  failedResult: ["عملیات ناموفق بود. جزئیات را در گزارش عملیات بررسی کنید.", "The operation failed. Check the activity log for details."],
  unknownResult: ["نتیجه نامشخص است. پیش از اقدام دوباره، گزارش عملیات و تلگرام را بررسی کنید.", "The outcome is unknown. Check the activity log and Telegram before taking action again."],
  successResult: ["درخواست با موفقیت ثبت شد.", "The request was recorded successfully."],
  resultWarning: ["عملیات با هشدار ثبت شد. جزئیات را در گزارش عملیات و تلگرام بررسی کنید.", "The operation returned a warning. Check the activity log and Telegram for details."],
  networkError: ["پاسخ معتبری دریافت نشد؛ نتیجه ممکن است نامشخص باشد. برای تلاش مجدد با همان شناسه، فرم را تغییر ندهید و صفحه را نبندید.", "No valid response was received; the outcome may be unknown. Keep this page open and leave the form unchanged to retry with the same request ID."],
  logout: ["خروج از حساب", "Sign out"],
  loggingOut: ["در حال خروج…", "Signing out…"],
  logoutError: ["خروج انجام نشد. دوباره تلاش کنید.", "Sign out failed. Please try again."],
  succeeded: ["موفق", "Succeeded"],
  failed: ["ناموفق", "Failed"],
  unknown: ["نامشخص", "Unknown"],
  pending: ["در انتظار", "Pending"],
  recordedStatus: ["وضعیت ثبت‌شده", "Recorded status"],
  recordedAction: ["عملیات ثبت‌شده", "Recorded action"],
  publishAction: ["انتشار پست", "Publish post"],
  settingsAction: ["تغییر تنظیمات کانال", "Change chat settings"],
  reviewAction: ["بررسی هشدار", "Review alert"],
} as const satisfies Record<string, readonly [string, string]>;

export type DashboardCopy = { [Key in keyof typeof copy]: string };

export function dashboardCopy(locale: Locale): DashboardCopy {
  return Object.fromEntries(Object.entries(copy).map(([key, values]) => [key, values[locale === "fa" ? 0 : 1]])) as DashboardCopy;
}

export function statusLabel(locale: Locale, status: string): string {
  const c = dashboardCopy(locale);
  const labels: Record<string, string> = { SUCCEEDED: c.succeeded, FAILED: c.failed, UNKNOWN: c.unknown, PENDING: c.pending };
  return labels[status.toUpperCase()] ?? c.recordedStatus;
}

export function actionLabel(locale: Locale, action: string): string {
  const c = dashboardCopy(locale);
  const labels: Record<string, string> = { ban: c.ban, unban: c.unban, publish: c.publishAction, sync: c.sync, attach: c.attach, settings: c.settingsAction, connect: c.connect, review: c.reviewAction };
  return labels[action.toLowerCase()] ?? c.recordedAction;
}

export function mutationError(locale: Locale, status: number, error: unknown, detail?: unknown): string {
  const c = dashboardCopy(locale);
  if (status === 409) return c.conflictError;
  if (typeof error === "string" && error.trim() && (locale === "fa" || !/[\u0600-\u06ff]/.test(error))) return error;
  // The localized message was unusable here, but Telegram's own description is
  // English and is usually the one line that says what to fix.
  if (typeof detail === "string" && detail.trim()) return `${c.requestError} (${detail.trim().slice(0, 200)})`;
  return c.requestError;
}
